apiVersion: v1
kind: Service
metadata:
  name: glances-external
  namespace: homepage
  annotations:
    httproute.controller/expose: "true"
    httproute.controller/hostname: "glances.homelab.local"
spec:
  ports:
    - port: 80
      targetPort: 61208
---
apiVersion: v1
kind: Endpoints
metadata:
  name: glances-external
  namespace: homepage
subsets:
  - addresses:
      - ip: 192.168.178.75
    ports:
      - port: 61208
