---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-api-key
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: immich-api-key
    creationPolicy: Owner
  data:
    - secretKey: api-key
      remoteRef:
        key: ae1960e5-4102-43a4-9718-b3ba00fd2684
