---
# ExternalSecret for Authentik PostgreSQL password
# After pushing with PushSecret, use this to pull from Bitwarden
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-postgresql
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-postgresql
    creationPolicy: Owner
  data:
  - secretKey: password
    remoteRef:
      key: 83ccdff4-3411-4be5-be63-b39600fd3156
---
# ExternalSecret for Authentik secret key
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret-key
  namespace: authentik
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: authentik-secret-key
    creationPolicy: Owner
  data:
  - secretKey: AUTHENTIK_SECRET_KEY
    remoteRef:
      key: c70d780c-d3bb-49cc-8d8f-b39600fd0c65
