---
apiVersion: v1
kind: ConfigMap
metadata:
  name: cloudflared-immich
  namespace: cloudflare-tunnel
data:
  config.yaml: |
    tunnel: 0990f7e5-0002-4227-ad8d-15016ceb859e
    credentials-file: /etc/cloudflared/creds/credentials.json
    metrics: 0.0.0.0:2000
    ingress:
      - hostname: immich.cloudrumble.net
        service: http://immich-server.immich.svc.cluster.local:2283
        originRequest:
          noTLSVerify: false
          connectTimeout: 30s
          keepAliveTimeout: 90s
          http2Origin: false
      - service: http_status:404
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudflared-immich
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared-immich
spec:
  replicas: 2
  selector:
    matchLabels:
      app: cloudflared-immich
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: cloudflared-immich
    spec:
      containers:
      - name: cloudflared
        image: cloudflare/cloudflared:latest
        args:
        - tunnel
        - --config
        - /etc/cloudflared/config/config.yaml
        - --metrics
        - 0.0.0.0:2000
        - run
        ports:
        - name: metrics
          containerPort: 2000
          protocol: TCP
        livenessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 3
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /ready
            port: 2000
          failureThreshold: 3
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "200m"
        volumeMounts:
        - name: config
          mountPath: /etc/cloudflared/config
          readOnly: true
        - name: creds
          mountPath: /etc/cloudflared/creds
          readOnly: true
      volumes:
      - name: config
        configMap:
          name: cloudflared-immich
          items:
          - key: config.yaml
            path: config.yaml
      - name: creds
        secret:
          secretName: tunnel-credentials-immich
---
apiVersion: v1
kind: Service
metadata:
  name: cloudflared-immich-metrics
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared-immich
spec:
  selector:
    app: cloudflared-immich
  ports:
  - name: metrics
    port: 2000
    targetPort: 2000
    protocol: TCP
  type: ClusterIP
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: cloudflared-immich
  namespace: cloudflare-tunnel
  labels:
    app: cloudflared-immich
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app: cloudflared-immich
  endpoints:
  - port: metrics
    interval: 30s
    path: /metrics
