---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tunnel-credentials-immich
  namespace: cloudflare-tunnel
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: tunnel-credentials-immich
    creationPolicy: Owner
  data:
    - secretKey: credentials.json
      remoteRef:
        key: dd2a4074-241c-42ce-840f-b3ba00f34e26
