# Custom values for kagent Helm chart deployment
# Based on homelab requirements with resource limits and Ollama configuration

# ==============================================================================
# GLOBAL CONFIGURATION
# ==============================================================================

tag: ""
registry: "cr.kagent.dev"

imagePullPolicy: IfNotPresent
namespaceOverride: "kagent"

# ==============================================================================
# DATABASE CONFIGURATION
# ==============================================================================

database:
  type: sqlite
  sqlite:
    databaseName: kagent.db

# ==============================================================================
# CONTROLLER CONFIGURATION
# ==============================================================================

controller:
  replicas: 1
  loglevel: "info"
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 2000m
      memory: 512Mi
  service:
    type: LoadBalancer
    ports:
      port: 8083
      targetPort: 8083

# ==============================================================================
# UI CONFIGURATION
# ==============================================================================

ui:
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  service:
    type: LoadBalancer
    ports:
      port: 80
      targetPort: 8080

# ==============================================================================
# LLM PROVIDERS CONFIGURATION
# ==============================================================================

providers:
  default: ollama
  openAI:
    provider: OpenAI
    model: "gpt-4o-mini"
    apiKeySecretRef: kagent-openai
    apiKeySecretKey: OPENAI_API_KEY
    apiKey: "sk-ollama-only"  # Dummy value for Ollama-only setup
  ollama:
    provider: Ollama
    model: "gpt-oss:latest"
    config:
      host: "http://192.168.178.81:11434"

# ==============================================================================
# BUILT-IN TOOLS
# ==============================================================================

kagent-tools:
  fullnameOverride: kagent-tools
  enabled: true
  replicaCount: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 500m
      memory: 512Mi

# ==============================================================================
# AGENTS - Disable unnecessary ones to save memory
# ==============================================================================

agents:
  # Core agents - KEEP ENABLED
  k8s-agent:
    enabled: true
  observability-agent:
    enabled: true
  helm-agent:
    enabled: true
  promql-agent:
    enabled: true  # Required by observability-agent
  
  # DISABLE unnecessary agents to save memory
  argo-rollouts-agent:
    enabled: false
  cilium-debug-agent:
    enabled: false
  cilium-manager-agent:
    enabled: false
  cilium-policy-agent:
    enabled: false
  istio-agent:
    enabled: false
  kgateway-agent:
    enabled: false

# ==============================================================================
# EXTERNAL MCP SERVERS
# ==============================================================================

querydoc:
  enabled: true
  replicas: 1
  resources:
    requests:
      cpu: 100m
      memory: 256Mi
    limits:
      cpu: 1000m
      memory: 512Mi
  openai:
    apiKey: "sk-ollama-only"  # Dummy value for Ollama-only setup

# ==============================================================================
# OBSERVABILITY
# ==============================================================================

otel:
  tracing:
    enabled: false
  logging:
    enabled: false