---
# ExternalSecret for Homepage
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secrets
  namespace: homepage
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: homepage-secrets
    creationPolicy: Owner
  data:
  - secretKey: argocd-token
    remoteRef:
      key: homepage/config
      property: argocd_token
  - secretKey: grafana-password
    remoteRef:
      key: homepage/config
      property: grafana_password
---
# ExternalSecret for MinIO
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: minio-secrets
  namespace: minio
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault-backend
    kind: SecretStore
  target:
    name: minio-secrets
    creationPolicy: Owner
  data:
  - secretKey: root-user
    remoteRef:
      key: minio/config
      property: root_user
  - secretKey: root-password
    remoteRef:
      key: minio/config
      property: root_password
