# Vault Helm Chart Values - Production Configuration
# CRITICAL: Using persistent storage to prevent data loss

injector:
  enabled: false

server:
  # DISABLE DEV MODE - THIS USES IN-MEMORY STORAGE!
  dev:
    enabled: false
  
  # Enable persistent storage
  dataStorage:
    enabled: true
    size: 10Gi
    storageClass: default
    
  # Production configuration
  standalone:
    enabled: true
    config: |
      ui = true
      
      listener "tcp" {
        tls_disable = 1
        address = "[::]:8200"
        cluster_address = "[::]:8201"
      }
      
      # Use file storage instead of in-memory
      storage "file" {
        path = "/vault/data"
      }
      
      # Auto-unseal configuration can be added later
      seal "shamir" {}
      
      disable_mlock = true
      api_addr = "http://vault.vault.svc.cluster.local:8200"
      cluster_addr = "http://vault.vault.svc.cluster.local:8201"

ui:
  enabled: true
  serviceType: LoadBalancer
  loadBalancerIP: 192.168.178.92

# Resource limits
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 512Mi
    cpu: 500m