---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: kubeview-sse-timeout
  namespace: envoy-gateway-system
spec:
  targetRefs:
    - group: gateway.networking.k8s.io
      kind: HTTPRoute
      name: kubeview-kubeview
  timeout:
    http:
      requestTimeout: 0s
      connectionIdleTimeout: 3600s
