---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shell-operator
  namespace: metallb-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shell-operator-metallb
rules:
- apiGroups: [""]
  resources: ["pods", "pods/log"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["daemonsets"]
  verbs: ["get", "list", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shell-operator-metallb
subjects:
- kind: ServiceAccount
  name: shell-operator
  namespace: metallb-system
roleRef:
  kind: ClusterRole
  name: shell-operator-metallb
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shell-operator
  namespace: metallb-system
  labels:
    app: shell-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shell-operator
  template:
    metadata:
      labels:
        app: shell-operator
    spec:
      serviceAccountName: shell-operator
      containers:
      - name: shell-operator
        image: piotrzan/shell-operator-metallb:v3
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: run
          mountPath: /var/run/shell-operator
      volumes:
      - name: run
        emptyDir: {}
