---
# Forgejo Helm Chart Values
# Based on CONTRACT.md from Phase 1 proof-of-concept

gitea:
  admin:
    # Credentials pulled from ExternalSecret (forgejo-admin-credentials)
    existingSecret: forgejo-admin-credentials

  config:
    server:
      DOMAIN: git.homelab.local
      ROOT_URL: http://git.homelab.local
      HTTP_PORT: 3000
      DISABLE_SSH: false
      SSH_PORT: 22
      START_SSH_SERVER: true
      LFS_START_SERVER: true

    database:
      DB_TYPE: sqlite3

    repository:
      ROOT: /data/git/repositories
      ENABLE_PUSH_CREATE_USER: true

    security:
      INSTALL_LOCK: true

    service:
      DISABLE_REGISTRATION: false
      REQUIRE_SIGNIN_VIEW: false

    metrics:
      ENABLED: true

# Use Forgejo image instead of Gitea
image:
  registry: code.forgejo.org
  repository: forgejo/forgejo
  tag: ""
  pullPolicy: IfNotPresent
  rootless: true

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
  accessModes:
    - ReadWriteOnce

service:
  http:
    type: LoadBalancer
    port: 3000
  ssh:
    type: ClusterIP
    port: 22

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

# Ingress disabled - using LoadBalancer
ingress:
  enabled: false

# Disable external dependencies (using SQLite)
postgresql:
  enabled: false

redis-cluster:
  enabled: false

memcached:
  enabled: false
