---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: git-mirror-storage
  namespace: git-mirror
  labels:
    app: git-mirror-sync
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 20Gi
