---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: github-token
  namespace: git-mirror
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: github-token
    creationPolicy: Owner
  refreshInterval: 1h
  data:
  - secretKey: token
    remoteRef:
      key: 7b5d53a8-05e7-4082-93ec-b37b00a9303f
      property: github-pat-exporter
