apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ai-inference
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Piotr1215/homelab
    targetRevision: HEAD
    path: gitops/apps/ai-inference
  destination:
    server: https://kubernetes.default.svc
    namespace: ai-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
