---
# Single bootstrap Application that loads all ApplicationSets
# This is NOT app-of-apps - it just watches the appsets folder
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: appsets-loader
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: HEAD
    path: gitops/appsets
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
    retry:
      limit: 3
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 1m
