---
# Core infrastructure components (networking, storage, monitoring)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: infrastructure
  namespace: argocd
spec:
  description: Core infrastructure components
  sourceRepos:
  - https://github.com/Piotr1215/homelab
  - https://prometheus-community.github.io/helm-charts
  - https://grafana.github.io/helm-charts
  - https://metallb.github.io/metallb
  - https://kubernetes-sigs.github.io/metrics-server/
  destinations:
  - namespace: metallb-system
    server: https://kubernetes.default.svc
  - namespace: prometheus
    server: https://kubernetes.default.svc
  - namespace: loki
    server: https://kubernetes.default.svc
  - namespace: cluster-scanning
    server: https://kubernetes.default.svc
  - namespace: kube-system
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: admin
    policies:
    - p, proj:infrastructure:admin, applications, *, infrastructure/*, allow
    groups:
    - argocd-admins
---
# Platform services (secrets, certificates, ingress)
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: platform
  namespace: argocd
spec:
  description: Platform services and utilities
  sourceRepos:
  - https://github.com/Piotr1215/homelab
  - https://charts.external-secrets.io
  - https://charts.jetstack.io
  - https://kubernetes.github.io/ingress-nginx
  - https://helm.releases.hashicorp.com
  destinations:
  - namespace: vault
    server: https://kubernetes.default.svc
  - namespace: cert-manager
    server: https://kubernetes.default.svc
  - namespace: external-secrets
    server: https://kubernetes.default.svc
  - namespace: ingress-nginx
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: admin
    policies:
    - p, proj:platform:admin, applications, *, platform/*, allow
    groups:
    - argocd-admins
---
# User-facing applications
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: applications
  namespace: argocd
spec:
  description: User-facing applications
  sourceRepos:
  - https://github.com/Piotr1215/homelab
  destinations:
  - namespace: homepage
    server: https://kubernetes.default.svc
  - namespace: minio
    server: https://kubernetes.default.svc
  - namespace: default
    server: https://kubernetes.default.svc
  - namespace: '*'
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  roles:
  - name: admin
    policies:
    - p, proj:applications:admin, applications, *, applications/*, allow
    groups:
    - argocd-admins
  - name: readonly
    policies:
    - p, proj:applications:readonly, applications, get, applications/*, allow
    groups:
    - developers