apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: envoy-gateway-resources
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: main
    path: gitops/apps/envoy-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: envoy-gateway-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
