apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  source:
    chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: 4.15.1
    helm:
      values: |
        # Driver configuration - using modern eBPF probe (default)
        driver:
          enabled: true
          kind: modern_ebpf

        # Controller configuration
        controller:
          kind: daemonset
          daemonset:
            updateStrategy:
              type: RollingUpdate

        # Resource limits appropriate for homelab
        resources:
          requests:
            cpu: 100m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 1024Mi

        # Falco configuration
        falco:
          # Enable gRPC output for future integrations
          grpc:
            enabled: true
            bind_address: "unix:///run/falco/falco.sock"
            threadiness: 0

          # Enable HTTP output for webhook integrations
          http_output:
            enabled: false
            url: ""

          # Metrics configuration - native Prometheus support
          metrics:
            enabled: true
            interval: 1h
            output_rule: true
            rules_counters_enabled: true
            resource_utilization_enabled: true
            state_counters_enabled: true
            kernel_event_counters_enabled: true
            libbpf_stats_enabled: true
            plugins_metrics_enabled: true

          # JSON output for better parsing
          json_output: true
          json_include_output_property: true
          json_include_tags_property: true

          # Log stderr and syslog
          log_stderr: true
          log_syslog: true
          log_level: info

          # Priority levels to log
          priority: debug

          # Disable config file watching to avoid inotify issues
          watch_config_files: false

        # Disable falcoctl automatic rules updates (use bundled rules)
        falcoctl:
          artifact:
            install:
              enabled: false
            follow:
              enabled: false

        # Falcosidekick for event routing and Web UI
        falcosidekick:
          enabled: true
          webui:
            enabled: true
            replicaCount: 1
            service:
              type: LoadBalancer
              port: 2802
            resources:
              requests:
                cpu: 50m
                memory: 64Mi
              limits:
                cpu: 200m
                memory: 128Mi

        # Enable ServiceMonitor for Prometheus scraping
        serviceMonitor:
          enabled: true
          interval: "30s"
          scrapeTimeout: "10s"
          additionalLabels: {}

        # Prometheus rules for alerting
        prometheusRules:
          enabled: true
          additionalLabels: {}

        # Grafana dashboard
        grafanaDashboard:
          enabled: true
          namespace: prometheus
          prometheusDatasourceName: Prometheus

        # Enable services
        services:
          - name: metrics
            type: ClusterIP
            ports:
              - port: 8765
                targetPort: 8765
                protocol: TCP
                name: metrics

        # Extra environment variables for better Kubernetes integration
        extra:
          env:
            - name: FALCO_HOSTNAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName

        # Tolerations to run on all nodes including control plane
        tolerations:
          - effect: NoSchedule
            key: node-role.kubernetes.io/control-plane
          - effect: NoSchedule
            key: node-role.kubernetes.io/master

        # Pod Security Context
        podSecurityContext:
          runAsUser: 0
          runAsGroup: 0
          fsGroup: 0

        # Container Security Context
        securityContext:
          privileged: true

  destination:
    server: https://kubernetes.default.svc
    namespace: falco

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
