apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infrastructure
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  project: infrastructure
  source:
    repoURL: https://github.com/Piotr1215/homelab
    targetRevision: HEAD
    path: gitops/argocd-apps
  destination:
    server: https://kubernetes.default.svc
  ignoreDifferences:
  - group: ""
    kind: PersistentVolumeClaim
    namespace: cluster-scanning
    jsonPointers:
    - /spec
    - /status
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true