apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx
  namespace: argocd
spec:
  project: platform
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.13.3   # pick a stable version
    helm:
      releaseName: ingress-nginx
      values: |
        controller:
          service:
            type: LoadBalancer
            loadBalancerIP: "192.168.178.91"
            annotations:
              metallb.universe.tf/loadBalancerIPs: "192.168.178.91"
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
