apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: default
  source:
    chart: k8s-gateway
    repoURL: https://ori-edge.github.io/k8s_gateway
    targetRevision: 2.3.3
    helm:
      values: |
        # Domain for all Kubernetes resources
        domain: home.arpa

        # DNS server configuration
        service:
          type: LoadBalancer
          loadBalancerIP: 192.168.178.103
          port: 53
          protocol: UDP

        # Watch for LoadBalancer Services only
        watchedResources:
          - Service

        # Resources
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
