---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8sgpt-instance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: main
    path: gitops/apps/k8sgpt
  destination:
    server: https://kubernetes.default.svc
    namespace: k8sgpt-operator-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
