---
# ArgoCD Application for Vault with Persistent Storage
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vault
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
spec:
  project: platform
  source:
    repoURL: https://helm.releases.hashicorp.com
    targetRevision: 0.30.1
    chart: vault
    helm:
      values: |
        injector:
          enabled: false
        
        server:
          # CRITICAL: Disable dev mode to use persistent storage
          dev:
            enabled: false
          
          # Enable persistent storage
          dataStorage:
            enabled: true
            size: 10Gi
            storageClass: local-path
            
          # Production configuration
          standalone:
            enabled: true
            config: |
              ui = true
              
              listener "tcp" {
                tls_disable = 1
                address = "[::]:8200"
                cluster_address = "[::]:8201"
              }
              
              # Use file storage for persistence
              storage "file" {
                path = "/vault/data"
              }
              
              seal "shamir" {}
              
              disable_mlock = true
              api_addr = "http://vault.vault.svc.cluster.local:8200"
              cluster_addr = "http://vault.vault.svc.cluster.local:8201"
        
        ui:
          enabled: true
          serviceType: LoadBalancer
          loadBalancerIP: 192.168.178.92
        
        # Resource limits
        resources:
          requests:
            memory: 256Mi
            cpu: 250m
          limits:
            memory: 512Mi
            cpu: 500m
            
  destination:
    server: https://kubernetes.default.svc
    namespace: vault
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m