apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: vcluster-yaml-mcp-server
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
    # ArgoCD Image Updater configuration
    argocd-image-updater.argoproj.io/image-list: vcluster=piotrzan/vcluster-yaml-mcp-server
    argocd-image-updater.argoproj.io/vcluster.update-strategy: semver
    argocd-image-updater.argoproj.io/vcluster.allow-tags: regexp:^[0-9]+\.[0-9]+\.[0-9]+$
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/homelab-git-credentials
    argocd-image-updater.argoproj.io/git-branch: main
spec:
  project: applications
  source:
    repoURL: https://github.com/Piotr1215/homelab
    targetRevision: HEAD
    path: gitops/apps/vcluster-yaml-mcp-server
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
