---
apiVersion: core.k8sgpt.ai/v1alpha1
kind: K8sGPT
metadata:
  name: k8sgpt-local
  namespace: k8sgpt-operator-system
spec:
  ai:
    enabled: true
    model: gpt-oss
    backend: localai
    baseUrl: http://ollama-mac.ai-tools.svc.cluster.local:11434/v1
    anonymized: false
    language: english
    backOff:
      enabled: true
      maxRetries: 5
  noCache: false
  repository: ghcr.io/k8sgpt-ai/k8sgpt
  version: v0.4.26
  filters:
    - Pod
    - Deployment
    - ReplicaSet
    - PersistentVolumeClaim
    - Ingress
    - StatefulSet
    - CronJob
    - Node
    - Service
    - HorizontalPodAutoscaler
    - NetworkPolicy
