---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: spin-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  source:
    chart: spin-operator
    repoURL: oci://ghcr.io/spinframework/charts
    targetRevision: 0.6.1
  destination:
    server: https://kubernetes.default.svc
    namespace: spin-operator
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
