---
# PostgreSQL cluster with VectorChord extension for Immich
apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: immich-postgres
  namespace: immich
spec:
  instances: 1

  # pgvecto.rs image for Immich vector search (deprecated but compatible)
  imageName: ghcr.io/tensorchord/cloudnative-pgvecto.rs:16-v0.3.0

  enableSuperuserAccess: true

  postgresql:
    shared_preload_libraries:
      - "vectors.so"

  bootstrap:
    initdb:
      database: immich
      owner: immich
      secret:
        name: immich-postgres-user
      postInitSQL:
        - CREATE EXTENSION IF NOT EXISTS "vectors";
        - CREATE EXTENSION IF NOT EXISTS "cube" CASCADE;
        - CREATE EXTENSION IF NOT EXISTS "earthdistance" CASCADE;

  storage:
    size: 10Gi
    storageClass: longhorn

  resources:
    requests:
      memory: 512Mi
      cpu: 100m
    limits:
      memory: 2Gi
      cpu: "2"

  monitoring:
    enablePodMonitor: true

  # NOTE: CNPG S3 backup disabled - Garage S3 incompatible with barman-cloud (400 errors)
  # Using Longhorn daily snapshots instead (label on PVC: recurring-job.longhorn.io/backup-daily)
