---
# Initial credentials for CNPG cluster bootstrap
# After CNPG creates the cluster, it generates its own secret: immich-postgres-app
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: immich-postgres-user
    creationPolicy: Owner
  data:
    - secretKey: username
      remoteRef:
        key: immich-db-credentials
        property: username
    - secretKey: password
      remoteRef:
        key: immich-db-credentials
        property: password
