---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: immich-postgres-user
  namespace: immich
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: immich-postgres-user
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        username: '{{ .creds | fromJson | dig "username" "" }}'
        password: '{{ .creds | fromJson | dig "password" "" }}'
  data:
    - secretKey: creds
      remoteRef:
        key: 53fd61ab-1529-444d-b0ec-b3ba00ce981f
