---
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: externalsecret-defaults
spec:
  validationFailureAction: Audit
  background: false
  rules:
    - name: set-default-refresh-interval
      match:
        any:
          - resources:
              kinds:
                - ExternalSecret
      mutate:
        patchStrategicMerge:
          spec:
            refreshInterval: "24h"
