apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskchampion-sync-server-data
  labels:
    app.kubernetes.io/name: taskchampion-sync-server
    app.kubernetes.io/instance: taskchampion-sync-server
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
