---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: longhorn-tls
  namespace: longhorn-system
spec:
  secretName: longhorn-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  commonName: -longhorn.homelab.local
  dnsNames:
    - -longhorn.homelab.local
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
