---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: hubble-tls
  namespace: kube-system
spec:
  secretName: hubble-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  commonName: -hubble.homelab.local
  dnsNames:
    - -hubble.homelab.local
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
