---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: homepage-tls
  namespace: homepage
spec:
  secretName: homepage-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  commonName: -homepage.homelab.local
  dnsNames:
    - -homepage.homelab.local
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
