---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: harbor-tls
  namespace: harbor
spec:
  secretName: harbor-tls
  issuerRef:
    name: homelab-ca-issuer
    kind: ClusterIssuer
  commonName: harbor.homelab.local
  dnsNames:
    - harbor.homelab.local
  duration: 2160h  # 90 days
  renewBefore: 720h  # 30 days
