apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: homelab-gateway
  namespace: envoy-gateway-system
  annotations:
    cert-manager.io/cluster-issuer: homelab-ca-issuer
    argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
spec:
  gatewayClassName: envoy-gateway
  listeners:
  - name: http
    protocol: HTTP
    port: 80
    allowedRoutes:
      namespaces:
        from: All

  # HTTPS listener for TLS termination
  - name: https
    protocol: HTTPS
    port: 443
    hostname: "*.homelab.local"
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
        - kind: Secret
          name: homelab-gateway-tls
          namespace: envoy-gateway-system
