apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: harbor
  namespace: envoy-gateway-system
spec:
  parentRefs:
  - name: homelab-gateway
    namespace: envoy-gateway-system
    sectionName: https
  hostnames:
  - "harbor.homelab.local"
  rules:
  # Docker registry v2 API base endpoint (exact match)
  - matches:
    - path:
        type: PathPrefix
        value: /v2
    backendRefs:
    - name: harbor-core
      namespace: harbor
      port: 80
  # Docker registry v2 API operations (with trailing slash)
  - matches:
    - path:
        type: PathPrefix
        value: /v2/
    backendRefs:
    - name: harbor-registry
      namespace: harbor
      port: 5000
  # Harbor Core API
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: harbor-core
      namespace: harbor
      port: 80
  # Harbor UI controllers
  - matches:
    - path:
        type: PathPrefix
        value: /c
    backendRefs:
    - name: harbor-core
      namespace: harbor
      port: 80
  # Harbor service endpoints
  - matches:
    - path:
        type: PathPrefix
        value: /service
    backendRefs:
    - name: harbor-core
      namespace: harbor
      port: 80
  # Harbor Portal (UI) - catch all
  - matches:
    - path:
        type: PathPrefix
        value: /
    backendRefs:
    - name: harbor-portal
      namespace: harbor
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1beta1
kind: ReferenceGrant
metadata:
  name: harbor-backend
  namespace: harbor
spec:
  from:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    namespace: envoy-gateway-system
  to:
  - group: ""
    kind: Service
    name: harbor-portal
  - group: ""
    kind: Service
    name: harbor-core
  - group: ""
    kind: Service
    name: harbor-registry
