apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: prometheus
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 5m

    # Templates for notification formatting
    templates:
      - '/etc/alertmanager/config/*.tmpl'

    # Route configuration - defines how alerts are grouped and routed
    route:
      group_by: ['alertname', 'cluster', 'service']
      group_wait: 10s          # Wait before sending initial notification
      group_interval: 10s      # Wait before sending notification for new alerts in group
      repeat_interval: 12h     # Wait before resending notification
      receiver: 'default'      # Default receiver

      # Child routes for specific alert types
      routes:
        # Critical alerts - send immediately
        - match:
            severity: critical
          receiver: 'critical'
          continue: true         # Also send to default receiver
          group_wait: 0s
          repeat_interval: 4h

        # Warning alerts
        - match:
            severity: warning
          receiver: 'warning'
          group_wait: 30s
          repeat_interval: 12h

        # Storage alerts
        - match_re:
            alertname: '^(PersistentVolume.*|.*DiskPressure)$'
          receiver: 'storage'

        # Backup alerts
        - match_re:
            alertname: '^(VeleroBackup.*|VaultSnapshot.*)$'
          receiver: 'backup'

    # Inhibition rules - suppress alerts based on other alerts
    inhibit_rules:
      # Inhibit warning if critical is firing for same alertname
      - source_match:
          severity: 'critical'
        target_match:
          severity: 'warning'
        equal: ['alertname', 'namespace', 'pod']

    # Receivers - notification channels
    receivers:
      # Default receiver - change to your preferred notification method
      - name: 'default'
        # webhook_configs:
        #   - url: 'http://localhost:5001/'
        #     send_resolved: true

      # Critical alerts receiver
      - name: 'critical'
        # Example: Slack configuration (uncomment and configure)
        # slack_configs:
        #   - api_url: 'YOUR_SLACK_WEBHOOK_URL'
        #     channel: '#homelab-critical'
        #     title: 'CRITICAL: {{ .GroupLabels.alertname }}'
        #     text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
        #     send_resolved: true

        # Example: Discord configuration (uncomment and configure)
        # webhook_configs:
        #   - url: 'YOUR_DISCORD_WEBHOOK_URL'
        #     send_resolved: true

        # Example: Email configuration (uncomment and configure)
        # email_configs:
        #   - to: 'your-email@example.com'
        #     from: 'alertmanager@homelab.local'
        #     smarthost: 'smtp.gmail.com:587'
        #     auth_username: 'your-email@gmail.com'
        #     auth_password: 'your-app-password'
        #     require_tls: true

      # Warning alerts receiver
      - name: 'warning'
        # webhook_configs:
        #   - url: 'http://localhost:5001/'

      # Storage alerts receiver
      - name: 'storage'
        # webhook_configs:
        #   - url: 'http://localhost:5001/'

      # Backup alerts receiver
      - name: 'backup'
        # webhook_configs:
        #   - url: 'http://localhost:5001/'
