---
apiVersion: v1
kind: Service
metadata:
  name: forgejo-http
  namespace: git-mirror
  labels:
    app: forgejo
spec:
  type: LoadBalancer
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: forgejo
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: forgejo
  namespace: git-mirror
  labels:
    app: forgejo
    app.kubernetes.io/name: gitea
    app.kubernetes.io/instance: forgejo
spec:
  serviceName: forgejo
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: gitea
      app.kubernetes.io/instance: forgejo
  template:
    metadata:
      labels:
        app: forgejo
        app.kubernetes.io/name: gitea
        app.kubernetes.io/instance: forgejo
    spec:
      securityContext:
        fsGroup: 1000
      initContainers:
      - name: init-directories
        image: codeberg.org/forgejo/forgejo:11-rootless
        command: ["/bin/sh", "-c"]
        args:
        - |
          mkdir -p /data/git /data/forgejo/conf
          chown -R 1000:1000 /data
        volumeMounts:
        - name: data
          mountPath: /data
        securityContext:
          runAsUser: 0
      containers:
      - name: forgejo
        image: codeberg.org/forgejo/forgejo:11-rootless
        imagePullPolicy: IfNotPresent
        env:
        - name: USER_UID
          value: "1000"
        - name: USER_GID
          value: "1000"
        - name: GITEA__database__DB_TYPE
          value: "sqlite3"
        - name: GITEA__database__PATH
          value: "/data/forgejo/gitea.db"
        - name: GITEA__server__DOMAIN
          value: "git.homelab.local"
        - name: GITEA__server__ROOT_URL
          value: "http://git.homelab.local:3000"
        - name: GITEA__server__HTTP_PORT
          value: "3000"
        - name: GITEA__server__DISABLE_SSH
          value: "false"
        - name: GITEA__server__SSH_PORT
          value: "22"
        - name: GITEA__server__LFS_START_SERVER
          value: "true"
        - name: GITEA__repository__ROOT
          value: "/data/git/repositories"
        - name: GITEA__repository__ENABLE_PUSH_CREATE_USER
          value: "true"
        - name: GITEA__metrics__ENABLED
          value: "true"
        - name: GITEA__security__INSTALL_LOCK
          value: "true"
        - name: GITEA_ADMIN_USER
          valueFrom:
            secretKeyRef:
              name: forgejo-admin-credentials
              key: username
        - name: GITEA_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: forgejo-admin-credentials
              key: password
        - name: GITEA_ADMIN_EMAIL
          valueFrom:
            secretKeyRef:
              name: forgejo-admin-credentials
              key: email
        ports:
        - name: http
          containerPort: 3000
        - name: ssh
          containerPort: 22
        livenessProbe:
          httpGet:
            path: /api/healthz
            port: http
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /api/healthz
            port: http
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 100m
            memory: 256Mi
        volumeMounts:
        - name: data
          mountPath: /data
        securityContext:
          runAsUser: 1000
          runAsGroup: 1000
          runAsNonRoot: true
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: ["ReadWriteOnce"]
      storageClassName: local-path
      resources:
        requests:
          storage: 10Gi
