---
# Forgejo Helm Chart Values
# Based on CONTRACT.md from Phase 1 proof-of-concept

image:
  repository: codeberg.org/forgejo/forgejo
  tag: "11"
  rootless: true  # Security: run as non-root user

gitea:
  admin:
    # Credentials pulled from ExternalSecret (forgejo-admin-credentials)
    existingSecret: forgejo-admin-credentials

  config:
    database:
      DB_TYPE: sqlite3  # Embedded database, no external dependencies

    server:
      DOMAIN: git.homelab.local
      ROOT_URL: http://git.homelab.local
      HTTP_PORT: 3000
      DISABLE_SSH: false
      SSH_PORT: 22
      LFS_START_SERVER: true  # Enable Large File Storage

    repository:
      ROOT: /data/git/repositories
      ENABLE_PUSH_CREATE_USER: true

    service:
      DISABLE_REGISTRATION: false  # Can disable after initial setup

    metrics:
      ENABLED: true  # Enable Prometheus metrics endpoint

persistence:
  enabled: true
  size: 10Gi
  storageClass: local-path
  accessModes:
    - ReadWriteOnce

service:
  http:
    type: LoadBalancer
    port: 3000
  ssh:
    type: ClusterIP  # SSH not exposed via LoadBalancer per user config
    port: 22

resources:
  limits:
    cpu: 1000m
    memory: 1Gi
  requests:
    cpu: 100m
    memory: 256Mi

# Disable external dependencies (using SQLite)
postgresql:
  enabled: false
redis-cluster:
  enabled: false
