apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: github-exporter
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: default
  source:
    chart: github-exporter
    repoURL: https://promhippie.github.io/charts
    targetRevision: 7.0.12
    helm:
      values: |
        # Exporter configuration
        config:
          authType: token
          existingSecret: github-exporter-token
          tokenKey: token

        # Resources
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi

        # ServiceMonitor for Prometheus
        serviceMonitor:
          enabled: true
          labels:
            release: kube-prometheus-stack
          interval: 5m  # Scrape every 5 minutes (respect GitHub API rate limits)
          timeout: 4m30s  # Allow 4.5 minutes to fetch all repos from GitHub API

        # Specify which repos to scrape
        # Use comma-separated list: "owner/repo1,owner/repo2" or leave empty to scrape all accessible
        exporter:
          repos: "Piotr1215/homelab,Piotr1215/dotfiles,Piotr1215/vcluster-yaml-mcp,Piotr1215/cloudrumble,Piotr1215/mcp-obsidian,Piotr1215/presenterm.nvim,Piotr1215/kubectl-container,Piotr1215/pairup.nvim,Piotr1215/youtube,Piotr1215/beam.nvim,Piotr1215/terminal-slides-template,Piotr1215/aicmdtools,Piotr1215/typeit.nvim"

  destination:
    server: https://kubernetes.default.svc
    namespace: prometheus

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
