apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: infrastructure
  source:
    chart: harbor
    repoURL: https://helm.goharbor.io
    targetRevision: 1.16.1
    helm:
      valuesObject:
        expose:
          type: loadBalancer
          tls:
            enabled: false
          loadBalancer:
            name: harbor
            IP: 192.168.178.100
            ports:
              httpPort: 80
              httpsPort: 443

        externalURL: http://192.168.178.100

        # Persistence
        persistence:
          enabled: true
          persistentVolumeClaim:
            registry:
              storageClass: "local-path"
              size: 50Gi
            jobservice:
              storageClass: "local-path"
              size: 1Gi
            database:
              storageClass: "local-path"
              size: 5Gi
            redis:
              storageClass: "local-path"
              size: 1Gi
            trivy:
              storageClass: "local-path"
              size: 5Gi

        # Harbor admin credentials (change these!)
        harborAdminPassword: "Harbor12345"

        # Database (internal PostgreSQL)
        database:
          type: internal
          internal:
            password: "changeit"

        # Redis (internal)
        redis:
          type: internal

        # Core component
        core:
          replicas: 1
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m

        # Registry component
        registry:
          replicas: 1
          controller:
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
                cpu: 500m
          registry:
            resources:
              requests:
                memory: 256Mi
                cpu: 100m
              limits:
                memory: 512Mi
                cpu: 500m

        # Trivy vulnerability scanner
        trivy:
          enabled: true
          replicas: 1
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              cpu: 1000m
              memory: 1Gi

        # Chartmuseum for Helm charts
        chartmuseum:
          enabled: true
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m

        # Notary for image signing (optional, disabled for simplicity)
        notary:
          enabled: false

        # Portal (web UI)
        portal:
          replicas: 1
          resources:
            requests:
              memory: 128Mi
              cpu: 100m
            limits:
              memory: 256Mi
              cpu: 200m

        # Jobservice for async tasks
        jobservice:
          replicas: 1
          resources:
            requests:
              memory: 256Mi
              cpu: 100m
            limits:
              memory: 512Mi
              cpu: 500m

  destination:
    server: https://kubernetes.default.svc
    namespace: harbor

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
