---
apiVersion: v1
kind: Namespace
metadata:
  name: kube-janitor
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-janitor
  namespace: kube-janitor
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: kube-janitor
rules:
- apiGroups: [""]
  resources: ["events"]
  verbs: ["create"]
- apiGroups: ["*"]
  resources: ["*"]
  verbs: ["get", "list", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: kube-janitor
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: kube-janitor
subjects:
- kind: ServiceAccount
  name: kube-janitor
  namespace: kube-janitor
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: kube-janitor-rules
  namespace: kube-janitor
data:
  rules.yaml: |
    # Clean up completed jobs older than 7 days
    - id: cleanup-completed-jobs
      resources:
        - jobs
      jmespath: "status.completionTime && (status.succeeded > `0` || status.failed > `0`)"
      ttl: 7d
    
    # Clean up failed jobs older than 3 days
    - id: cleanup-failed-jobs
      resources:
        - jobs
      jmespath: "status.failed > `0`"
      ttl: 3d
    
    # Clean up succeeded pods not owned by anything
    - id: cleanup-orphaned-pods
      resources:
        - pods
      jmespath: "status.phase == 'Succeeded' && !metadata.ownerReferences"
      ttl: 1d
    
    # Clean up evicted pods immediately
    - id: cleanup-evicted-pods
      resources:
        - pods
      jmespath: "status.phase == 'Failed' && status.reason == 'Evicted'"
      ttl: 0
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-janitor
  namespace: kube-janitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kube-janitor
  template:
    metadata:
      labels:
        app: kube-janitor
    spec:
      serviceAccountName: kube-janitor
      containers:
      - name: kube-janitor
        image: hjacobs/kube-janitor:23.7.0
        args:
          - --interval=300
          - --grace-period=86400
          - --dry-run=false
          - --rules-file=/config/rules.yaml
          - --exclude-namespaces=kube-system,kube-public,kube-node-lease
          - --exclude-resources=secrets,configmaps,persistentvolumeclaims
        resources:
          limits:
            memory: 100Mi
            cpu: 50m
          requests:
            memory: 50Mi
            cpu: 10m
        volumeMounts:
        - name: rules
          mountPath: /config
          readOnly: true
      volumes:
      - name: rules
        configMap:
          name: kube-janitor-rules