---
# Kyverno Policy Library - Pod Security Standards
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno-policies
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    chart: kyverno-policies
    repoURL: https://kyverno.github.io/kyverno/
    targetRevision: 3.3.11
    helm:
      valuesObject:
        # Pod Security Standards - Baseline Profile
        # More permissive, good starting point
        podSecurityStandard: baseline

        # Validation failure action
        # Options: Audit (log only) or Enforce (block)
        validationFailureAction: Audit  # Start with Audit mode

        # Background scanning for existing resources
        background: true

        # Exclude system namespaces
        exclude:
          any:
          - resources:
              namespaces:
              - kyverno
              - kube-system
              - kube-public
              - kube-node-lease
              - cert-manager
              - metallb-system
              - local-path-storage
              - calico-system
              - calico-apiserver

  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=false  # Kyverno namespace already exists
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
