apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: loki
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: loki
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 6.44.0
    helm:
      values: |
        # Deploy Loki in SingleBinary mode (perfect for homelab)
        deploymentMode: SingleBinary

        loki:
          # Enable structured metadata and log volume API
          schemaConfig:
            configs:
              - from: 2024-04-01
                store: tsdb
                object_store: filesystem
                schema: v13
                index:
                  prefix: loki_index_
                  period: 24h

          # Configure storage
          storage:
            type: 'filesystem'
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules

          # Enable log volume API and set limits
          limits_config:
            retention_period: 168h  # 7 days retention
            volume_enabled: true
            max_cache_freshness_per_query: 10m
            split_queries_by_interval: 15m
            query_timeout: 300s

          # Disable multi-tenancy (single-tenant mode for homelab)
          auth_enabled: false

          # Resource limits
          commonConfig:
            replication_factor: 1  # Single binary mode

          # Storage retention
          compactor:
            retention_enabled: true
            delete_request_store: filesystem

          # Ruler configuration for alerting
          ruler:
            enable_api: true
            enable_alertmanager_v2: true
            alertmanager_url: http://kube-prometheus-stack-alertmanager.prometheus.svc.cluster.local:9093
            storage:
              type: local
              local:
                directory: /var/loki/rules
            rule_path: /tmp/rules
            ring:
              kvstore:
                store: inmemory

        # SingleBinary configuration
        singleBinary:
          replicas: 1
          persistence:
            enabled: true
            storageClass: local-path
            size: 10Gi
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 1
              memory: 1Gi
          extraVolumes:
            - name: loki-rules
              configMap:
                name: loki-vcluster-mcp-rules
          extraVolumeMounts:
            - name: loki-rules
              mountPath: /var/loki/rules/fake
              readOnly: true

        # Disable other deployment modes
        backend:
          replicas: 0
        read:
          replicas: 0
        write:
          replicas: 0

        # ServiceMonitor for Prometheus metrics
        monitoring:
          serviceMonitor:
            enabled: true
            labels:
              release: kube-prometheus-stack
          selfMonitoring:
            enabled: false
            grafanaAgent:
              installOperator: false
          lokiCanary:
            enabled: false

        # Disable loki-canary (test pods that spam logs)
        lokiCanary:
          enabled: false

        # Disable cache components (not needed for SingleBinary)
        chunksCache:
          enabled: false
        resultsCache:
          enabled: false

        # Configure test framework
        test:
          enabled: false

        # Gateway configuration
        gateway:
          enabled: false

  destination:
    server: https://kubernetes.default.svc
    namespace: loki

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
