# Patch for Loki Promtail RBAC
# This ensures proper permissions for Promtail to scrape logs cluster-wide
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: loki-stack-promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: loki-stack
rules:
  - apiGroups:
      - ""
    resources:
      - nodes
      - nodes/proxy
      - services
      - endpoints
      - pods
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: loki-stack-promtail
  labels:
    app.kubernetes.io/name: promtail
    app.kubernetes.io/instance: loki-stack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: loki-stack-promtail
subjects:
  - kind: ServiceAccount
    name: loki-stack-promtail
    namespace: loki-stack  # Correct namespace for the ServiceAccount