---
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - first-pool
  # Advertise from all nodes to ensure redundancy
  nodeSelectors:
  - matchLabels:
      kubernetes.io/os: linux
  # Ensure proper interface selection
  interfaces:
  - ens18  # Primary network interface on your nodes
---
# Update IPAddressPool with better configuration
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: first-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.178.90-192.168.178.110
  autoAssign: true
  avoidBuggyIPs: false
  # Add service allocation priority
  serviceAllocation:
    priority: 100
    namespaces:
    - homepage
    - argocd
    - ingress-nginx
    - monitoring
    - prometheus
    - default
    - minio
    - portainer
    - vault
    - kube-system
