---
# Single pool for all services - much simpler!
apiVersion: metallb.io/v1beta1
kind: IPAddressPool
metadata:
  name: main-pool
  namespace: metallb-system
spec:
  addresses:
  - 192.168.178.90-192.168.178.110
  autoAssign: true
---
# Pin all services to kube-worker2 to prevent speaker node flapping
# This fixes the issue where IPs flip between nodes causing ARP confusion
# See: https://github.com/metallb/metallb/issues/1972 and Obsidian notes
apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: l2-advert
  namespace: metallb-system
spec:
  ipAddressPools:
  - main-pool
  interfaces:
  - ens18
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: kube-worker2
