apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: renovate
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"
spec:
  project: infrastructure
  source:
    chart: renovate
    repoURL: https://docs.renovatebot.com/helm-charts
    targetRevision: 44.15.1
    helm:
      values: |
        cronjob:
          schedule: "0 */2 * * *"  # Run every 2 hours

        # Increase Node.js heap size for large repos
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

        renovate:
          # Use existing renovate.json config from repository
          config: |
            {
              "platform": "github",
              "repositories": ["Piotr1215/homelab"],
              "onboarding": false,
              "requireConfig": "optional"
            }

        # Use existing secret for GitHub token
        existingSecret: renovate-github-token

        # Resource limits
        resources:
          requests:
            cpu: 200m
            memory: 512Mi
          limits:
            cpu: 1000m
            memory: 2Gi

        # Security context
        securityContext:
          fsGroup: 1000
          runAsUser: 1000
          runAsNonRoot: true

        # Pod annotations for monitoring
        podAnnotations:
          prometheus.io/scrape: "false"

  destination:
    server: https://kubernetes.default.svc
    namespace: renovate

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
