apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: renovate-github-token
  namespace: renovate
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: renovate-github-token
    creationPolicy: Owner
  refreshInterval: 1h
  data:
  - secretKey: token
    remoteRef:
      key: 451fe94e-2d1e-4360-a998-b382015e4774
      property: value
