---
# RuntimeClass for Spin applications using containerd-shim-spin
# This tells Kubernetes to use the Spin runtime instead of runc
apiVersion: node.k8s.io/v1
kind: RuntimeClass
metadata:
  name: wasmtime-spin-v2
handler: spin
scheduling:
  nodeSelector:
    spin: "true"
  tolerations:
    - key: "spin"
      operator: "Equal"
      value: "true"
      effect: "NoSchedule"
