apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tempo
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  project: default
  source:
    chart: tempo
    repoURL: https://grafana.github.io/helm-charts
    targetRevision: 1.24.0
    helm:
      values: |
        # Deploy Tempo in monolithic mode (perfect for homelab)
        tempo:
          repository: grafana/tempo
          tag: 2.8.2

          # Storage configuration
          storage:
            trace:
              backend: local
              local:
                path: /var/tempo/traces

          # Retention configuration (7 days like Loki)
          retention: 168h

          # Receiver protocols - accept traces from OpenTelemetry
          receivers:
            otlp:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:4317
                http:
                  endpoint: 0.0.0.0:4318
            jaeger:
              protocols:
                grpc:
                  endpoint: 0.0.0.0:14250
                thrift_http:
                  endpoint: 0.0.0.0:14268
            zipkin:
              endpoint: 0.0.0.0:9411

          # Metrics configuration with TraceQL metrics (local-blocks)
          metricsGenerator:
            enabled: true
            remoteWriteUrl: "http://kube-prometheus-stack-prometheus.prometheus.svc.cluster.local:9090/api/v1/write"

          # Enable local-blocks processor for TraceQL metrics
          overrides:
            defaults:
              metrics_generator:
                processors: [local-blocks]

        # Persistence for traces
        persistence:
          enabled: true
          storageClassName: local-path
          size: 10Gi

        # Service configuration
        service:
          type: ClusterIP

        # ServiceMonitor for Prometheus metrics
        serviceMonitor:
          enabled: true
          labels:
            release: kube-prometheus-stack

        # Resource limits
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 2
            memory: 2Gi

  destination:
    server: https://kubernetes.default.svc
    namespace: tempo

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
