---
# Simple Vault Raft Backup CronJob
# Uses root token directly from secret
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vault-backups
  namespace: vault
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: local-path
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: vault-backup
  namespace: vault
spec:
  schedule: "0 2 * * *"  # Daily at 2 AM
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      ttlSecondsAfterFinished: 3600  # Keep jobs for 1 hour after completion
      template:
        spec:
          restartPolicy: OnFailure
          volumes:
            - name: backup
              persistentVolumeClaim:
                claimName: vault-backups
          containers:
            - name: snapshot
              image: hashicorp/vault:1.17.6
              command:
                - /bin/sh
                - -c
                - |
                  set -e
                  TIMESTAMP=$(date +%Y%m%d-%H%M%S)
                  SNAPSHOT_FILE="/backups/vault-snapshot-${TIMESTAMP}.snap"
                  
                  echo "Taking Vault snapshot at ${TIMESTAMP}..."
                  vault operator raft snapshot save "${SNAPSHOT_FILE}"
                  
                  if [ -f "${SNAPSHOT_FILE}" ]; then
                    echo "Snapshot saved successfully: ${SNAPSHOT_FILE}"
                    ls -lh "${SNAPSHOT_FILE}"
                    
                    # Keep only last 30 snapshots
                    echo "Cleaning old snapshots..."
                    cd /backups
                    ls -t vault-snapshot-*.snap 2>/dev/null | tail -n +31 | xargs -r rm -v
                    
                    echo "Current snapshots:"
                    ls -lh vault-snapshot-*.snap | head -10
                  else
                    echo "ERROR: Snapshot file not created!"
                    exit 1
                  fi
              env:
                - name: VAULT_ADDR
                  value: "http://vault-0.vault-internal:8200"
                - name: VAULT_TOKEN
                  valueFrom:
                    secretKeyRef:
                      name: vault-root-token
                      key: token
              volumeMounts:
                - name: backup
                  mountPath: /backups