---
# Helm chart apps with external sources
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: apps-helm
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
    - list:
        elements:
          - app: kubernetes-dashboard
            namespace: kubernetes-dashboard
            chartRepo: https://kubernetes.github.io/dashboard/
            chartName: kubernetes-dashboard
            chartVersion: "7.14.0"
            createNamespace: "false"
            project: cluster-management
          - app: forgejo
            namespace: git-mirror
            chartRepo: oci://code.forgejo.org/forgejo-helm/forgejo
            chartName: forgejo
            chartVersion: "8.0.0"
            createNamespace: "false"
          - app: pyroscope
            namespace: pyroscope
            chartRepo: https://grafana.github.io/helm-charts
            chartName: pyroscope
            chartVersion: "1.16.0"
            createNamespace: "true"
            project: observability
          - app: longhorn
            namespace: longhorn-system
            chartRepo: https://charts.longhorn.io
            chartName: longhorn
            chartVersion: "1.10.1"
            createNamespace: "true"
            project: storage
          - app: cert-manager
            namespace: cert-manager
            chartRepo: https://charts.jetstack.io
            chartName: cert-manager
            chartVersion: "v1.19.1"
            createNamespace: "true"
            project: cluster-management
          - app: external-secrets
            namespace: external-secrets
            chartRepo: https://charts.external-secrets.io
            chartName: external-secrets
            chartVersion: "0.20.4"
            createNamespace: "true"
            serverSideApply: "true"
            project: security
          - app: kube-prometheus-stack
            namespace: prometheus
            chartRepo: https://prometheus-community.github.io/helm-charts
            chartName: kube-prometheus-stack
            chartVersion: "79.6.1"
            createNamespace: "true"
            serverSideApply: "true"
            project: observability
          - app: loki
            namespace: loki
            chartRepo: https://grafana.github.io/helm-charts
            chartName: loki
            chartVersion: "6.46.0"
            createNamespace: "true"
            project: observability
          - app: tempo
            namespace: tempo
            chartRepo: https://grafana.github.io/helm-charts
            chartName: tempo
            chartVersion: "1.24.0"
            createNamespace: "true"
            project: observability
          - app: promtail
            namespace: loki
            chartRepo: https://grafana.github.io/helm-charts
            chartName: promtail
            chartVersion: "6.17.1"
            createNamespace: "false"
            project: observability
          - app: envoy-gateway
            namespace: envoy-gateway-system
            chartRepo: oci://docker.io/envoyproxy/gateway-helm
            chartName: gateway-helm
            chartVersion: "v1.6.0"
            createNamespace: "true"
            serverSideApply: "true"
            disableMigration: "true"
            project: networking
          - app: argocd-image-updater
            namespace: argocd
            chartRepo: https://argoproj.github.io/argo-helm
            chartName: argocd-image-updater
            chartVersion: "0.14.0"
            createNamespace: "false"
            project: cluster-management
          - app: argo-rollouts
            namespace: argo-rollouts
            chartRepo: https://argoproj.github.io/argo-helm
            chartName: argo-rollouts
            chartVersion: "2.40.5"
            createNamespace: "true"
            project: cluster-management
            serverSideApply: "true"
          - app: authentik
            namespace: authentik
            chartRepo: https://charts.goauthentik.io
            chartName: authentik
            chartVersion: "2025.10.2"
            createNamespace: "false"
            project: security
          - app: beyla
            namespace: tempo
            chartRepo: https://grafana.github.io/helm-charts
            chartName: beyla
            chartVersion: "1.9.9"
            createNamespace: "false"
            project: observability
          - app: falco
            namespace: falco
            chartRepo: https://falcosecurity.github.io/charts
            chartName: falco
            chartVersion: "4.15.1"
            createNamespace: "true"
            project: security
          - app: kyverno
            namespace: kyverno
            chartRepo: https://kyverno.github.io/kyverno/
            chartName: kyverno
            chartVersion: "3.6.1"
            createNamespace: "true"
            serverSideApply: "true"
            project: security
          - app: k8sgpt-operator
            namespace: k8sgpt-operator-system
            chartRepo: https://charts.k8sgpt.ai/
            chartName: k8sgpt-operator
            chartVersion: "0.2.24"
            createNamespace: "true"
            project: apps
          - app: metrics-server
            namespace: kube-system
            chartRepo: https://kubernetes-sigs.github.io/metrics-server/
            chartName: metrics-server
            chartVersion: "3.13.0"
            createNamespace: "false"
            project: observability
          - app: opentelemetry-collector
            namespace: tempo
            chartRepo: https://open-telemetry.github.io/opentelemetry-helm-charts
            chartName: opentelemetry-collector
            chartVersion: "0.140.0"
            createNamespace: "false"
            project: observability
          - app: github-exporter
            namespace: prometheus
            chartRepo: https://promhippie.github.io/charts
            chartName: github-exporter
            chartVersion: "7.0.13"
            createNamespace: "false"
            project: observability
          - app: harbor
            namespace: harbor
            chartRepo: https://helm.goharbor.io
            chartName: harbor
            chartVersion: "1.17.0"
            createNamespace: "true"
            project: storage
          - app: uptime-kuma
            namespace: uptime-kuma
            chartRepo: https://charts.pascaliske.dev
            chartName: uptime-kuma
            chartVersion: "2.4.0"
            createNamespace: "false"
            project: observability
          - app: cloudnative-pg
            namespace: cnpg-system
            chartRepo: https://cloudnative-pg.github.io/charts
            chartName: cloudnative-pg
            chartVersion: "0.27.0"
            createNamespace: "true"
            serverSideApply: "true"
            project: storage
          - app: immich
            namespace: immich
            chartRepo: oci://ghcr.io/immich-app/immich-charts/immich
            chartName: immich
            chartVersion: "0.10.3"
            createNamespace: "false"
            project: apps
  template:
    metadata:
      name: "{{ .app }}"
      finalizers:
        - resources-finalizer.argocd.argoproj.io
    spec:
      project: '{{ dig "project" "apps" . }}'
      sources:
        # Helm chart
        - repoURL: "{{ .chartRepo }}"
          chart: "{{ .chartName }}"
          targetRevision: "{{ .chartVersion }}"
          helm:
            releaseName: "{{ .app }}"
            valueFiles:
              - $values/gitops/apps/{{ .app }}/values.yaml
        # Values reference
        - repoURL: https://github.com/Piotr1215/homelab.git
          targetRevision: HEAD
          ref: values
        # Extra K8s resources
        - repoURL: https://github.com/Piotr1215/homelab.git
          targetRevision: HEAD
          path: gitops/apps/{{ .app }}
          directory:
            exclude: "values.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .namespace }}"
      ignoreDifferences:
        - group: ""
          kind: Service
          jqPathExpressions:
            - .metadata.annotations["metallb.universe.tf/ip-allocated-from-pool"]
            - .metadata.annotations["metallb.universe.tf/loadBalancerIPs"]
            - .status
            - .spec.ports[].nodePort
        - group: external-secrets.io
          kind: ExternalSecret
          jqPathExpressions:
            - .status
            - .metadata.resourceVersion
            - .metadata.generation
            - .metadata.finalizers
            - .spec.data[].remoteRef.conversionStrategy
            - .spec.data[].remoteRef.decodingStrategy
            - .spec.data[].remoteRef.metadataPolicy
        - group: apiextensions.k8s.io
          kind: CustomResourceDefinition
          jqPathExpressions:
            - .metadata.resourceVersion
            - .metadata.generation
            - .metadata.creationTimestamp
            - .metadata.uid
            - .metadata.annotations["kubectl.kubernetes.io/last-applied-configuration"]
            - .status
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace={{ .createNamespace | default "false" }}
          - SkipDryRunOnMissingResource=true
          - RespectIgnoreDifferences=true
          - ApplyOutOfSyncOnly=true
          - ServerSideApply={{ dig "serverSideApply" "false" . }}
          - DisableClientSideApplyMigration={{ dig "disableMigration" "false" . }}
        retry:
          limit: 5
          backoff:
            duration: 5s
            factor: 2
            maxDuration: 3m
