---
apiVersion: v1
kind: Namespace
metadata:
  name: filegator
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: filegator-data
  namespace: filegator
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: filegator
  namespace: filegator
  labels:
    app: filegator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: filegator
  template:
    metadata:
      labels:
        app: filegator
    spec:
      containers:
      - name: filegator
        image: filegator/filegator:latest
        ports:
        - containerPort: 8080
          name: http
        volumeMounts:
        - name: data
          mountPath: /var/www/html/repository
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 8080
          initialDelaySeconds: 10
          periodSeconds: 5
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: filegator-data
---
apiVersion: v1
kind: Service
metadata:
  name: filegator
  namespace: filegator
  labels:
    app: filegator
spec:
  type: LoadBalancer
  selector:
    app: filegator
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
    name: http
