---
# Kagent CRDs ArgoCD Application
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent-crds
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  source:
    repoURL: ghcr.io/kagent-dev/kagent/helm
    chart: kagent-crds
    targetRevision: "*"  # Use latest version
    helm:
      releaseName: kagent-crds
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m

---
# Kagent Main Application using Helm
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kagent
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "10"
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  
  # Multiple sources for Helm chart and values from Git
  sources:
    # Main Helm chart
    - repoURL: ghcr.io/kagent-dev/kagent/helm
      chart: kagent
      targetRevision: "*"  # Use latest version
      helm:
        releaseName: kagent
        valueFiles:
          - $values/gitops/apps/kagent/values.yaml
    
    # Values file from Git repo
    - repoURL: https://github.com/Piotr1215/homelab
      targetRevision: HEAD
      ref: values
  
  destination:
    server: https://kubernetes.default.svc
    namespace: kagent
  
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - ServerSideApply=true
      - RespectIgnoreDifferences=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  
  # Ignore differences for certain fields that are managed dynamically
  ignoreDifferences:
    - group: ""
      kind: Service
      jsonPointers:
        - /spec/clusterIP
        - /spec/clusterIPs
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
