apiVersion: kagent.dev/v1alpha1
kind: ModelConfig
metadata:
  name: gpt-oss-model-config
  namespace: kagent
spec:
  apiKeySecretKey: OPENAI_API_KEY
  apiKeySecretRef: kagent-openai
  model: gpt-oss:latest
  provider: Ollama
  ollama:
    host: http://192.168.178.81:11434
  # Required: Specify model capabilities
  modelInfo:
    vision: false
    functionCalling: true
    jsonOutput: true
    family: "unknown"
    structuredOutput: true
    multipleSystemMessages: false