apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-datasource
  namespace: prometheus
  labels:
    grafana_datasource: "1"
    app: kube-prometheus-stack-grafana
data:
  loki-datasource.yaml: |
    apiVersion: 1
    datasources:
    - name: "Loki"
      type: loki
      uid: loki
      url: http://loki-stack.loki.svc.cluster.local:3100
      access: proxy
      isDefault: false
      jsonData:
        maxLines: 1000
