apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "1"  # Deploy after basic infra
spec:
  project: default
  source:
    chart: longhorn
    repoURL: https://charts.longhorn.io
    targetRevision: 1.10.0
    helm:
      releaseName: longhorn
      valuesObject:
        defaultSettings:
          defaultReplicaCount: "2"  # 2 replicas for 2 healthy nodes
          replicaSoftAntiAffinity: "true"
          backupTarget: "nfs://192.168.178.60:/volume1/Kubernetes/longhorn-backups"
          autoDeletePodWhenVolumeDetachedUnexpectedly: "true"
          createDefaultDiskLabeledNodes: "true"
          autoSalvage: "true"
          guaranteedEngineManagerCPU: "12"
          guaranteedReplicaManagerCPU: "12"
        persistence:
          defaultClass: true
          defaultClassReplicaCount: "2"
        service:
          ui:
            type: LoadBalancer
            loadBalancerIP: "192.168.178.105"
            annotations:
              metallb.universe.tf/loadBalancerIPs: "192.168.178.105"
        csi:
          attacherReplicaCount: "2"
          provisionerReplicaCount: "2"
          resizerReplicaCount: "2"
          snapshotterReplicaCount: "2"
        longhornManager:
          priorityClass: system-cluster-critical
        longhornDriver:
          priorityClass: system-cluster-critical
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system

  ignoreDifferences:
    - group: ""
      kind: Service
      name: longhorn-frontend
      jsonPointers:
        - /metadata/annotations/metallb.universe.tf~1ip-allocated-from-pool
        - /status/loadBalancer/ingress
        - /spec/ports/0/nodePort

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - SkipDryRunOnMissingResource=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 5m
