apiVersion: v1
kind: ConfigMap
metadata:
  name: loki-vcluster-mcp-rules
  namespace: loki
data:
  vcluster-mcp-access.yaml: |
    groups:
      - name: vcluster-mcp-access
        interval: 10s
        rules:
          - alert: VClusterMCPAccessed
            expr: |
              sum by (ip) (count_over_time({namespace="default", pod=~"vcluster-yaml-mcp.*"} |= "MCP POST request from" | pattern `MCP POST request from <ip>` [10s])) > 0
            for: 0s
            labels:
              severity: info
              component: vcluster-mcp
            annotations:
              summary: "vCluster MCP accessed from {{ $labels.ip }}"
              description: "Client IP {{ $labels.ip }} is using vcluster-yaml-mcp-server"
