apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: vcluster-mcp-alerts
  namespace: prometheus
  labels:
    release: kube-prometheus-stack
    prometheus: kube-prometheus-stack-prometheus
    role: alert-rules
spec:
  groups:
  - name: vcluster-mcp-usage
    interval: 30s
    rules:
    - alert: VClusterMCPServerUsed
      expr: |
        rate(container_network_receive_bytes_total{namespace="default",pod=~"vcluster-yaml-mcp.*"}[1m]) > 0
      for: 10s
      labels:
        severity: warning
        component: vcluster-mcp
      annotations:
        summary: "vCluster YAML MCP Server is being used"
        description: "Someone is actively using the vcluster-yaml-mcp server (network activity detected on pod {{ $labels.pod }})"
