---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: HEAD
    path: gitops/infra
    directory:
      include: '{git-mirror-namespace.yaml,forgejo*.yaml}'
  destination:
    server: https://kubernetes.default.svc
    namespace: git-mirror
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
