---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: forgejo
  namespace: argocd
spec:
  project: default
  sources:
  - repoURL: oci://code.forgejo.org/forgejo-helm
    chart: forgejo
    targetRevision: 11.0.1
    helm:
      valueFiles:
      - $values/gitops/forgejo/forgejo-values.yaml
  - repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: git-mirror
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
