---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kyverno
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
  # Source 1: Kyverno manifests (namespace, custom policies)
  - repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: HEAD
    path: gitops/kyverno
    directory:
      exclude: '{kyverno-values.yaml,policies-values.yaml,README.md}'
  # Source 2: Kyverno engine Helm chart
  - repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno
    targetRevision: 3.4.4
    helm:
      valueFiles:
      - $values/gitops/kyverno/kyverno-values.yaml
  # Source 3: Kyverno policies Helm chart
  - repoURL: https://kyverno.github.io/kyverno/
    chart: kyverno-policies
    targetRevision: 3.4.4
    helm:
      valueFiles:
      - $values/gitops/kyverno/policies-values.yaml
  # Source 4: Reference for value files
  - repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: HEAD
    ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: kyverno
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
