---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ntopng
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: applications
  source:
    repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: HEAD
    path: gitops/ntopng
  destination:
    server: https://kubernetes.default.svc
    namespace: ntopng
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
