---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: uptime-kuma
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: infrastructure
  sources:
  - repoURL: https://github.com/Piotr1215/homelab.git
    targetRevision: HEAD
    ref: values
  - repoURL: https://helm.irsigler.cloud
    chart: uptime-kuma
    targetRevision: "2.22.0"
    helm:
      valueFiles:
      - $values/gitops/uptime-kuma/uptime-kuma-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
