apiVersion: v1
kind: Secret
metadata:
  name: homelab-repo
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/Piotr1215/homelab
  username: Piotr1215
  password: YOUR_GITHUB_PAT_HERE  # Replace with your GitHub Personal Access Token