apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: backup-daily
  namespace: longhorn-system
spec:
  concurrency: 2
  cron: "0 2 * * *"
  groups:
    - default
  labels:
    recurring-job: backup-daily
  retain: 7
  task: backup
