---
apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: tailscale-oauth
  namespace: tailscale
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: bitwarden-secretsmanager
  target:
    name: operator-oauth
    creationPolicy: Owner
  data:
    - secretKey: client_id
      remoteRef:
        key: 03b4c20d-3dc0-4ef7-8fda-b3ba0118da82
    - secretKey: client_secret
      remoteRef:
        key: 2d4ac36d-1d95-4962-883b-b3ba011f5ddc
