---
apiVersion: v1
kind: Service
metadata:
  name: tempo-headless
  namespace: tempo
  labels:
    app.kubernetes.io/name: tempo
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: tempo
  ports:
  - name: http
    port: 3100
    protocol: TCP
    targetPort: 3100
