---
apiVersion: v1
kind: Service
metadata:
  name: hubble-ui-lb
  namespace: kube-system
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: hubble-ui
  ports:
    - name: http
      port: 80
      targetPort: 8081