apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: audit-latest-tag
  annotations:
    policies.kyverno.io/title: Audit Latest Tag Usage
    policies.kyverno.io/category: Best Practices
    policies.kyverno.io/description: >-
      Reports when images use 'latest' or no tag.
      Audit mode - doesn't block, just reports.
spec:
  validationFailureAction: Audit
  background: true
  rules:
    - name: audit-latest-tag
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Image '{{request.object.spec.containers[].image}}' uses 'latest' tag or no tag. Consider pinning to a specific version."
        pattern:
          spec:
            containers:
              - image: "*:*"
    - name: audit-mutable-tags
      match:
        any:
          - resources:
              kinds:
                - Pod
      validate:
        message: "Image uses mutable tag (latest, main, master, dev). Consider using immutable tags or digests."
        deny:
          conditions:
            any:
              - key: "{{ regex_match('^.*:(latest|main|master|dev)$', request.object.spec.containers[0].image) }}"
                operator: Equals
                value: true
