---
# ArgoCD ConfigMap - With Authentik SSO via Dex
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Homepage account configuration
  accounts.homepage: apiKey,login
  accounts.homepage.enabled: "true"
  # Application instance label
  application.instanceLabelKey: argocd.argoproj.io/instance

  # ArgoCD URL - HTTPS!
  url: https://argocd.homelab.local

  # Dex configuration for Authentik OIDC
  dex.config: |
    connectors:
    - config:
        issuer: https://authentik.homelab.local/application/o/argo-cd/
        clientID: cC5rwGcBk5ooxqE0cNyVhoznI4qXshZaVaOhajSA
        clientSecret: $dex.authentik.clientSecret
        insecureEnableGroups: true
        insecureSkipVerify: true
        scopes:
          - openid
          - profile
          - email
      name: authentik
      type: oidc
      id: authentik
