---
# System-level ignoreDifferences to handle ServerSideApply drift
# See: https://argo-cd.readthedocs.io/en/stable/user-guide/diffing/#system-level-configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Ignore status fields globally (common source of drift)
  resource.compareoptions: |
    ignoreResourceStatusField: all
  # Ignore fields managed by kube-controller-manager (common for StatefulSets, Deployments)
  resource.customizations.ignoreDifferences.all: |
    managedFieldsManagers:
    - kube-controller-manager
  # Ignore MetalLB runtime annotations and nodePort on Services
  resource.customizations.ignoreDifferences._Service: |
    jqPathExpressions:
    - '.metadata.annotations["metallb.universe.tf/ip-allocated-from-pool"]'
    - '.spec.ports[].nodePort'
  # Ignore fields on ExternalSecrets (defaults added by ESO controller)
  resource.customizations.ignoreDifferences.external-secrets.io_ExternalSecret: |
    jqPathExpressions:
    - '.metadata.finalizers'
    - '.spec.data[].remoteRef.conversionStrategy'
    - '.spec.data[].remoteRef.decodingStrategy'
    - '.spec.data[].remoteRef.metadataPolicy'
    - '.spec.target.deletionPolicy'
  # Ignore caBundle in webhooks (injected by cert-manager)
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_MutatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  resource.customizations.ignoreDifferences.admissionregistration.k8s.io_ValidatingWebhookConfiguration: |
    jqPathExpressions:
    - '.webhooks[]?.clientConfig.caBundle'
  # Custom health checks for Gateway API resources
  resource.customizations.health.gateway.networking.k8s.io_Gateway: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Programmed" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = condition.message
            return hs
          end
          if condition.type == "Accepted" and condition.status == "False" then
            hs.status = "Degraded"
            hs.message = condition.message
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for Gateway to be programmed"
    return hs
  resource.customizations.health.gateway.networking.k8s.io_HTTPRoute: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.parents ~= nil then
        for i, parent in ipairs(obj.status.parents) do
          if parent.conditions ~= nil then
            for j, condition in ipairs(parent.conditions) do
              if condition.type == "Accepted" and condition.status == "True" then
                hs.status = "Healthy"
                hs.message = "HTTPRoute accepted"
                return hs
              end
            end
          end
        end
      end
    end
    hs.status = "Progressing"
    hs.message = "Waiting for HTTPRoute to be accepted"
    return hs
  resource.customizations.health.gateway.envoyproxy.io_EnvoyProxy: |
    hs = {}
    hs.status = "Healthy"
    hs.message = "EnvoyProxy configuration applied"
    return hs
  resource.customizations.health.gateway.networking.k8s.io_GatewayClass: |
    hs = {}
    if obj.status ~= nil then
      if obj.status.conditions ~= nil then
        for i, condition in ipairs(obj.status.conditions) do
          if condition.type == "Accepted" and condition.status == "True" then
            hs.status = "Healthy"
            hs.message = condition.message
            return hs
          end
        end
      end
    end
    hs.status = "Progressing"
    return hs
  resource.customizations.health.gateway.networking.k8s.io_ReferenceGrant: |
    hs = {}
    hs.status = "Healthy"
    return hs
