---
# ArgoCD ConfigMap - Minimal safe configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
data:
  # Minimal placeholder to prevent deletion
  # Add custom settings here as needed
  application.instanceLabelKey: argocd.argoproj.io/instance
