---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: argocd-authentik
  namespace: argocd
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: bitwarden-secretsmanager
    kind: ClusterSecretStore
  target:
    name: argocd-secret
    creationPolicy: Merge  # Merge into existing argocd-secret
    template:
      mergePolicy: Merge
      metadata:
        labels:
          app.kubernetes.io/part-of: argocd
  data:
  - secretKey: dex.authentik.clientSecret
    remoteRef:
      key: argocd-authentik-client-secret
