apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: argocd-backend-tls
  namespace: argocd
spec:
  targetRefs:
  - group: ""
    kind: Service
    name: argocd-server
  validation:
    caCertificateRefs:
    - name: argocd-backend-ca-cm
      kind: ConfigMap
      group: ""
    hostname: argocd-server.argocd.svc.cluster.local
