# Phase 2: Policy matches correct namespace
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-memory-limits
spec:
  rules:
  - name: require-memory-limits
    match:
      any:
      - resources:
          namespaces:
          - cnpe-security-test
