apiVersion: v1
kind: Namespace
metadata:
  name: cnpe-security-test
---
# BROKEN: Policy doesn't block pods - needs fixing
apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: require-memory-limits
  namespace: cnpe-security-test
spec:
  # BUG 1: Should be "Enforce" to block violations
  validationFailureAction: Audit
  background: true
  rules:
  - name: require-memory-limits
    match:
      any:
      - resources:
          kinds:
          - Pod
          namespaces:
          # BUG 2: Wrong namespace - should be "cnpe-security-test"
          - cnpe-other-namespace
    validate:
      message: "Memory limits are required for all containers."
      pattern:
        spec:
          containers:
          - resources:
              limits:
                memory: "?*"
