---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-monitor-script
  namespace: monitoring
data:
  check-nas.sh: |
    #!/bin/bash
    set -eo pipefail

    NAS_IP="192.168.178.138"
    NAS_PORT="5000"
    NTFY_TOPIC="https://ntfy.sh/homelab-piotr1215-backup"
    STATE_FILE="/tmp/nas-state"

    # Function to send ntfy alert
    send_alert() {
      local title="$1"
      local message="$2"
      local priority="${3:-4}"
      local tags="${4:-warning}"

      curl -s -X POST "$NTFY_TOPIC" \
        -H "Title: $title" \
        -H "Priority: $priority" \
        -H "Tags: $tags" \
        -d "$message" || true
    }

    # Check ping
    if ! ping -c 2 -W 3 "$NAS_IP" >/dev/null 2>&1; then
      if [ ! -f "$STATE_FILE" ] || [ "$(cat $STATE_FILE)" != "down" ]; then
        send_alert "ðŸ”´ NAS Unreachable" \
          "Synology NAS at $NAS_IP is not responding to ping. Check network connectivity and NAS power." \
          5 "rotating_light,warning,nas"
        echo "down" > "$STATE_FILE"
      fi
      exit 0
    fi

    # Check HTTP port
    if ! timeout 5 bash -c "cat < /dev/null > /dev/tcp/$NAS_IP/$NAS_PORT" 2>/dev/null; then
      if [ ! -f "$STATE_FILE" ] || [ "$(cat $STATE_FILE)" != "port-down" ]; then
        send_alert "âš ï¸ NAS Port Unreachable" \
          "Synology NAS at $NAS_IP:$NAS_PORT is not responding. DSM service may be down." \
          4 "warning,nas"
        echo "port-down" > "$STATE_FILE"
      fi
      exit 0
    fi

    # NAS is healthy - send recovery alert if it was down
    if [ -f "$STATE_FILE" ] && [ "$(cat $STATE_FILE)" != "up" ]; then
      send_alert "âœ… NAS Recovered" \
        "Synology NAS at $NAS_IP is now reachable." \
        1 "white_check_mark,nas"
      echo "up" > "$STATE_FILE"
    elif [ ! -f "$STATE_FILE" ]; then
      echo "up" > "$STATE_FILE"
    fi
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: nas-monitor
  namespace: monitoring
spec:
  schedule: "*/5 * * * *"  # Every 5 minutes
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        metadata:
          labels:
            app: nas-monitor
        spec:
          restartPolicy: Never
          containers:
          - name: checker
            image: nicolaka/netshoot:latest
            command: ["/bin/bash", "/scripts/check-nas.sh"]
            volumeMounts:
            - name: script
              mountPath: /scripts
            - name: state
              mountPath: /tmp
            resources:
              requests:
                cpu: 10m
                memory: 32Mi
              limits:
                cpu: 100m
                memory: 64Mi
            securityContext:
              allowPrivilegeEscalation: false
              runAsNonRoot: true
              runAsUser: 1000
              capabilities:
                drop:
                - ALL
                add:
                - NET_RAW  # Required for ping
              seccompProfile:
                type: RuntimeDefault
          volumes:
          - name: script
            configMap:
              name: nas-monitor-script
              defaultMode: 0755
          - name: state
            emptyDir: {}
