---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nas-monitor-state
  namespace: monitoring
data:
  state: "unknown"
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nas-monitor
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: nas-monitor
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  resourceNames: ["nas-monitor-state"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nas-monitor
  namespace: monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: nas-monitor
subjects:
- kind: ServiceAccount
  name: nas-monitor
  namespace: monitoring
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nas-monitor
  namespace: monitoring
  labels:
    app: nas-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nas-monitor
  template:
    metadata:
      labels:
        app: nas-monitor
    spec:
      serviceAccountName: nas-monitor
      containers:
      - name: shell-operator
        image: piotrzan/shell-operator-nas-monitor:v1
        imagePullPolicy: Always
        resources:
          requests:
            cpu: 10m
            memory: 64Mi
          limits:
            cpu: 100m
            memory: 128Mi
        securityContext:
          allowPrivilegeEscalation: false
          runAsNonRoot: true
          runAsUser: 1000
          capabilities:
            drop:
            - ALL
          seccompProfile:
            type: RuntimeDefault
        volumeMounts:
        - name: run
          mountPath: /var/run/shell-operator
      volumes:
      - name: run
        emptyDir: {}
