---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope-lb
  namespace: pyroscope
  labels:
    app: pyroscope
  # IP auto-assigned by MetalLB: 192.168.178.110
spec:
  type: LoadBalancer
  selector:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/instance: pyroscope
  ports:
  - name: http
    port: 4040
    targetPort: 4040
    protocol: TCP
