---
apiVersion: v1
kind: Service
metadata:
  name: argocd-application-controller
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-application-controller
    app.kubernetes.io/component: application-controller
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: argocd-application-controller
  ports:
  - name: metrics
    port: 8082
    protocol: TCP
    targetPort: 8082
