---
apiVersion: v1
kind: Service
metadata:
  name: pyroscope-lb
  namespace: pyroscope
  labels:
    app: pyroscope
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pyroscope
    app.kubernetes.io/instance: pyroscope
  ports:
  - name: http
    port: 4040
    targetPort: 4040
    protocol: TCP
