---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pyroscope
  namespace: pyroscope
  labels:
    app: pyroscope
    release: kube-prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pyroscope
  endpoints:
  - port: http-metrics
    interval: 30s
    path: /metrics
