---
# Patch to configure default-model-config for Ollama
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: default-model-config
  namespace: kagent
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  model: gpt-oss:latest
  provider: Ollama
  ollama:
    host: http://192.168.178.81:11434