---
# Custom Kagent Configuration for Ollama-only setup
apiVersion: v1
kind: Namespace
metadata:
  name: kagent
---
# Secret for API key (dummy for Ollama-only usage)
apiVersion: v1
kind: Secret
metadata:
  name: kagent-openai
  namespace: kagent
type: Opaque
stringData:
  OPENAI_API_KEY: "sk-ollama-only-no-openai"
---
# Default ModelConfig - Points to Ollama
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: default-model-config
  namespace: kagent
  labels:
    app.kubernetes.io/name: kagent
    app.kubernetes.io/part-of: kagent
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  model: gpt-oss:latest
  provider: Ollama
  ollama:
    host: http://192.168.178.81:11434
---
# Additional Ollama ModelConfig
apiVersion: kagent.dev/v1alpha2
kind: ModelConfig
metadata:
  name: gpt-oss-model-config
  namespace: kagent
spec:
  apiKeySecret: kagent-openai
  apiKeySecretKey: OPENAI_API_KEY
  model: gpt-oss:latest
  provider: Ollama
  ollama:
    host: http://192.168.178.81:11434
---
# LoadBalancer Service for Controller
apiVersion: v1
kind: Service
metadata:
  name: kagent-controller
  namespace: kagent
  annotations:
    metallb.universe.tf/loadBalancerIPs: 192.168.178.102
spec:
  type: LoadBalancer
